traectory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.contrib.auth.decorators import login_required

from .user.views import UserListView, UserCreate
from .event.views import EventListView
from .traectory.views import ProgramListView

urlpatterns = patterns('',
    url(r'^users/$', login_required(UserListView.as_view()), name='users'),
    url(r'^$', UserCreate.as_view(), name='create_user'),

    url(r'^events/$', EventListView.as_view(), name='create_user'),
    url(r'^programs/$', ProgramListView.as_view(), name='programs_list'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

trajectory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from django.contrib.auth.decorators import login_required

from .user.views import UserListView, new_user
from .event.views import EventListView
from .trajectory.views import trajectory_view, trajectory_save, stats
from .files.views import user_files, delete
from .contest.views import create_contest_item, read_contest_item_all, read_contest_item, create_contest_item_rank

urlpatterns = patterns('',
                       url(r'^users/$', login_required(UserListView.as_view()), name='users'),
                       url(r'^$', new_user, name='create_user'),
                       url(r'^tr/(?P<pk>.+)/$', trajectory_view, name='trajectoryView'),
                       url(r'^save/$', trajectory_save, name='trajectorySave'),
                       url(r'^stats/$', stats, name='stats'),
                       url(r'^files/(?P<pk>.+)/$', user_files, name='Files'),
                       url(r'^delete/(?P<pk>.+)/(?P<user_id>.+)/$', delete, name='delete'),
                       url(r'^events/$', EventListView.as_view(), name='create_user'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^contest/add_new/$', create_contest_item, name='create_contest_item'),
                       url(r'^contest/all/$', read_contest_item_all, name='read_contest_item_all'),
                       url(r'^contest/(?P<pk>\d+)/$', read_contest_item, name='read_contest_item'),
                       url(r'^contest/(?P<pk>\d+)/rank/$', create_contest_item_rank, name='create_contest_item_rank'),
                       )

urlpatterns += patterns('',
                        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT
                        }))

if settings.DEBUG404:
    urlpatterns += patterns('',
                            (r'^notv/static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT}
                            ),
    )

traectory/user/models.py
from django.db import models


class User(models.Model):
    i = models.CharField("Имя", max_length=1024)
    f = models.CharField("Фамилия", max_length=1024)
    o = models.CharField("Отчество", max_length=1024)
    city = models.CharField("Город", max_length=1024)
    email = models.EmailField("Электронная почта", max_length=1024)
    tel = models.CharField("Телефон", max_length=1024)
    #traectories = models.ManyToManyField()
    #files = models.ManyToManyField()
    online = 'online'
    offline = 'offline'
    STATUS = (
        (online, 'Заочно'),
        (offline, 'Очно')
    )
    status = models.CharField("Статус", max_length=7, choices=STATUS, default=offline)
    date = models.DateField(auto_now_add=True, blank=True)


    class Meta:
        unique_together = ("email", "f")

trajectory/contest/models.py
from django.db import models
from django.contrib.auth.models import User


class ContestItemRank(models.Model):
    user = models.ForeignKey(User)
    user_rank = models.IntegerField(
        "Оценка",
        max_length=8,
        blank=True,
        null=True
    )

    user_comment = models.CharField(
        "Комментарий",
        max_length=4096,
        blank=True,
        null=True
    )


class ContestItem(models.Model):

    ROUTES = (
        ('01', 'Лучший электронный курс'),
        ('02', 'Лучшее визуальное оформление курса'),
        ('03', 'Лучшая инновация в контроле знаний'),
    )

    route = models.CharField(
        "Номинация",
        max_length=2,
        choices=ROUTES
    )
    organization = models.CharField(
        "Организация",
        max_length=1024
    )
    city = models.CharField(
        "Город",
        max_length=1024
    )
    authors = models.CharField(
        "Авторы",
        max_length=1024
    )
    email = models.EmailField(
        "Электронная почта",
        max_length=1024
    )
    telephone = models.CharField(
        "Контактный телефон",
        max_length=1024
    )
    url = models.URLField(
        "Адрес ресурса",
        max_length=1024,
        blank=True,
        null=True
    )

    account = models.CharField(
        "Реквизиты доступа",
        max_length=1024,
        blank=True,
        null=True
    )

    description = models.CharField(
        "Описание основных идей",
        max_length=4096
    )

    rank = models.ManyToManyField(ContestItemRank)

    summary_rank = models.IntegerField(
        "Общая оценка",
        max_length=8,
        null=True,
        blank=True
    )

trajectory/event/models.py
import hashlib
from os import urandom
from django.db import models


def key():
    return hashlib.md5(urandom(128)).hexdigest()


class Event(models.Model):
    id = models.CharField(max_length=32, primary_key=True, default='None')
    name = models.CharField("Имя", max_length=1024)
    comment = models.TextField("Описание", max_length=4096, blank=True, null=True)
    startdate = models.DateTimeField(blank=True, null=True)
    enddate = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(verbose_name='Image', upload_to='images/%Y/%m', blank=True)

    def __str__(self):
        return self.name

    def save(self):
        if self.id == 'None':
            self.id = key()
        super(Event, self).save()

trajectory/files/models.py
import hashlib
from os import urandom, path
from datetime import datetime
import uuid
import time

from django.db import models

from ..user.models import User



def key():
    return hashlib.md5(urandom(128)).hexdigest()

def generate_new_filename(instance, filename):
    f, ext = path.splitext(filename)
    filename = '%s%s' % (uuid.uuid4().hex, ext)
    fullpath = 'files/' + time.strftime('%Y/%m') + '/' + filename
    return fullpath


class UserFile(models.Model):
    id = models.CharField(max_length=32, primary_key=True, default='None')
    name = models.CharField('Название', max_length=4096)
    file = models.FileField(verbose_name='User file', upload_to=generate_new_filename)
    date = models.DateField(auto_now_add=True, default=datetime.now())
    user = models.ForeignKey(User, blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self):
        if self.id == 'None':
            self.id = key()
        super(UserFile, self).save()

trajectory/user/models.py
from django.db import models
import hashlib
from os import urandom

from ..trajectory.models import Trajectory


def key():
    return hashlib.md5(urandom(128)).hexdigest()[:32]


class User(models.Model):
    id = models.CharField(max_length=32, primary_key=True, default='None')
    i = models.CharField("Имя", max_length=1024)
    f = models.CharField("Фамилия", max_length=1024)
    o = models.CharField("Отчество", max_length=1024)
    city = models.CharField("Город", max_length=1024)
    email = models.EmailField("Электронная почта", max_length=1024)
    tel = models.CharField("Телефон", max_length=1024)
    trajectories = models.ManyToManyField(Trajectory)
    link = models.CharField("Персональная ссылка", max_length=1024, blank=True, null=True)
    online = 'online'
    offline = 'offline'
    STATUS = (
        (online, 'Заочно'),
        (offline, 'Очно')
    )
    job = models.CharField("Должность", max_length=1024)
    org = models.CharField("Организация", max_length=1024)
    status = models.CharField("Статус", max_length=7, choices=STATUS, default=offline)
    date = models.DateField(auto_now_add=True, blank=True)

    class Meta:
        unique_together = ("email", "f")

    def save(self):
        if self.id == 'None':
            self.id = key()
        super(User, self).save()

trajectory/contest/forms.py
from django import forms
from .models import ContestItem, ContestItemRank


class ContestItemForm(forms.ModelForm):

    ROUTES = (
        ('01', 'Лучший электронный курс'),
        ('02', 'Лучшее визуальное оформление курса'),
        ('03', 'Лучшая инновация в контроле знаний'),
    )

    class Meta:
        model = ContestItem
        fields = [
            'route',
            'organization',
            'city',
            'authors',
            'email',
            'telephone',
            'url',
            'account',
            'description',
        ]


class ContestItemRankForm(forms.ModelForm):

    class Meta:
        model = ContestItemRank
        fields = [
            'user',
            'user_rank',
            'user_comment',
        ]

trajectory/user/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['i', 'f', 'o', 'org', 'job', 'city', 'email', 'tel', 'status']

trajectory/contest/views.py
from django.shortcuts import render, redirect
from django.core.context_processors import csrf
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from django.http import HttpResponse

from .models import ContestItem, ContestItemRank
from .forms import ContestItemForm, ContestItemRankForm

# CRUD


def create_contest_item(request):
    if request.method == 'POST':
        form = ContestItemForm(request.POST)
        if form.is_valid():
            contest_item = form.save(commit=False)
            contest_item.save()

            return render(request, 'contest/thanks.html')
        else:
            return HttpResponse('Invalid form')
    args = {}
    args.update(csrf(request))
    args['form'] = ContestItemForm()
    return render(request, 'contest/contest.html', args)


def read_contest_item_all(request):
    contest_items_ranking = {}
    contest_items = ContestItem.objects.all()
    for contest_item in contest_items:
        contest_items_ranking[contest_item.id] = []
        for rank in contest_item.rank.all():
            contest_items_ranking[contest_item.id].append(rank.user.id)

    return render(request, 'contest/contest_list.html', {
        "contest_items": contest_items,
        "contest_items_ranking": contest_items_ranking,
    })


def read_contest_item(request, pk):
    contest_item = get_object_or_404(ContestItem, pk=pk)
    return render(request, 'contest/contest_item.html', {
        'contest_item': contest_item,
    })


def update_contest_item(request, id):
    pass


def delete_contest_item(request, id):
    pass


@login_required()
def create_contest_item_rank(request, pk):

    if request.method == 'POST':
        form = ContestItemRankForm(request.POST)
        if form.is_valid():
            contest_item_rank = form.save(commit=False)
            contest_item_rank.save()

            contest_item_rank.user = User.objects.get(pk=request.user.id)
            contest_item_rank.save()

            contest_item = ContestItem.objects.get(pk=pk)
            contest_item.rank.add(contest_item_rank)
        else:
            return render(request, '500.html')
    args = {}
    args.update(csrf(request))
    args['form'] = ContestItemRankForm()
    return redirect('/contest/all/')

trajectory/event/views.py
from django.views.generic.list import ListView

from .models import Event


class EventListView(ListView):
    model = Event

trajectory/files/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from ..user.models import User
from .form import UserFileForm
from .models import UserFile


def user_files(request, pk):
    user = User.objects.get(pk=pk)
    form = UserFileForm

    if request.method == 'POST':
        form = UserFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.user = user
            form.save()

    files = UserFile.objects.filter(user=user)

    return render(request, 'files/files.html',
                  {
                      'user': user,
                      'form': form,
                      'files': files,

                  })


#@require_POST
def delete(request, pk, user_id):
    user = User.objects.get(pk=user_id)
    userfile = UserFile.objects.get(pk=pk)

    if userfile.user == user:
        userfile.delete()
        return redirect('/notv/files/' + user_id + '/')
    else:
        return render(request, 'error/forbidden.html')

trajectory/trajectory/views.py
import json

from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.admin.views.decorators import staff_member_required

from .models import Program, Trajectory, Cell
from ..user.models import User
from ..event.models import Event
from ..files.models import UserFile


def trajectory_view(request, pk=None):
    programs = Program.objects.all()
    active_events = []
    user = None
    if pk != None:
        trajectory = Trajectory.objects.get(pk=pk)
        user = User.objects.get(pk=trajectory.user_id)

        for event in trajectory.events.all():
            active_events.append(event.id)
    return render(request, 'trajectory/program_list.html',
                  {
                      'user': user,
                      'programs': programs,
                      'active_events': active_events,
                  })


@require_POST
def trajectory_save(request):
    trajectory_id = request.META['HTTP_REFERER'].split('/')[-2]
    trajectory = Trajectory.objects.get(pk=trajectory_id)

    trajectory.events.clear()

    data = request.POST.copy()
    data.pop('csrfmiddlewaretoken', None)
    data.pop('submit', None)

    cells_ids = []

    for item in data:
        cells_ids.append(item)
        event_id = data[item]
        try:
            user_event = Event.objects.get(pk=event_id)
        except ObjectDoesNotExist:
            user_event = 'None'
        if user_event:
            trajectory.events.add(user_event)

    cells = Cell.objects.filter(pk__in=cells_ids)

    for cell in cells:
        program_id = cell.program_set.all()

    programs = Program.objects.filter(pk__in=program_id)

    trajectory.comment = json.dumps(data)
    trajectory.save()

    user = User.objects.get(pk=trajectory.user_id)

    return render(request, 'trajectory/trajectory.html', {
        'user': user,
        'trajectory': trajectory,
        'cells': cells,
        'programs': programs
    })


@staff_member_required
def stats(request):
    event_users = {}
    event_users_status = {}
    event_users.clear()
    event_users_status.clear()
    events = Event.objects.all()
    for event in events:
        users_ids = []
        trajectories = event.trajectory_set.all()
        for trajectory in trajectories:
            users_ids.append(trajectory.user_id)
        users = User.objects.filter(pk__in=users_ids)
        event_users[event] = users

        for user in users:
            if event.id not in event_users_status.keys():
                event_users_status.update({event.id: []})
            event_users_status[event.id].append(user.status)
        event_users_status_json = json.dumps(event_users_status)

    number_users = User.objects.count()
    number_files = UserFile.objects.count()
    users = User.objects.order_by('f')

    userfiles = {}

    for user in users:
        files = UserFile.objects.filter(user=user)
        userfiles[user.id] = files

    return render(request, 'trajectory/stats.html', {
        'event_users': event_users,
        'number_users': number_users,
        'users': users,
        'userfiles': userfiles,
        'number_files': number_files,
        'event_users_status_json': event_users_status_json,
        }
    )

trajectory/user/views.py
from django.shortcuts import render, redirect
from django.core.context_processors import csrf
from django.utils import timezone
from django.views.generic.list import ListView
from django.core.mail import send_mail

from .models import User
from .forms import UserForm

from ..trajectory.models import Trajectory


class UserListView(ListView):
    model = User

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now
        return context


def new_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            trajectory = Trajectory()
            trajectory.user_id = user.id
            trajectory.save()

            link = 'http://openedu.urfu.ru/notv/tr/' + trajectory.id + '/'
            user.link = link
            user.save()
            try:
                send_mail('НОТВ 2015', 'Ваша персональная ссылка:'+link, 'info@notv.urfu.ru', [user.email])
            except:
                pass
            return redirect(link)
    args = {}
    args.update(csrf(request))
    args['form'] = UserForm()
    return render(request, 'user/user_form.html', args)

trajectory/templates/user/user_form.html
{% extends "base.html" %}
{% block content %}
<div class="for-footer">
<div class="main-title">


                <h1><span class="in"><span>Регистрация</span></span></h1>
            </div>

            <div class="section breadcrumbs">
                <div class="row">

                    <div class="col3">
                        <span class="breadcrumbs-item">
                            <a href="http://notv.urfu.ru/ru">Главная страница</a>
                        </span>
                        <span class="divide">/</span>
                        <span class="breadcrumbs-item">
                            <a href="{{user.link}}" class="no-underline">
                                <span>Регистрация</span>
                             </a>


                        </span>
                    </div>
                </div>
            </div>

<div class="section content">
   <div class="row">

      <div class="col2 lea_alex">
                  <header>
                    <h1 class="title">
                      <span class="title-super">Добро пожаловать!</span>
                    </h1>
                  </header>
            
   
    <form action="" method="post">

        {% csrf_token %}

        <div class="cont-input">
        <label for="id_f">Фамилия:</label>
        <input id="id_f" maxlength="1024" name="f" type="text">
        </div>

        <div class="cont-input">
        <label for="id_i">Имя:</label> 
        <input id="id_i" maxlength="1024" name="i" type="text">
        </div>

        <div class="cont-input">
        <label for="id_o">Отчество:</label>
        <input id="id_o" maxlength="1024" name="o" type="text">
        </div>

        <div class="cont-input">
        <label for="id_org">Организация:</label>
        <input id="id_org" maxlength="1024" name="org" type="text">
        </div>

        <div class="cont-input">
        <label for="id_job">Должность:</label>
        <input id="id_job" maxlength="1024" name="job" type="text">
        </div>

        <div class="cont-input">
        <label for="id_city">Город:</label>
        <input id="id_city" maxlength="1024" name="city" type="text">
        </div>

        <div class="cont-input">
        <label for="id_email">Электронная почта:</label>
        <input id="id_email" maxlength="1024" name="email" type="email">
        </div>

        <div class="cont-input">
        <label for="id_tel">Телефон:</label>
        <input id="id_tel" maxlength="1024" name="tel" type="text">
        </div>

        <div class="cont-input">
        <label for="id_status">Присутствие:</label>
        <select id="id_status" name="status">
            <option value="online">Заочно</option>
            <option value="offline" selected="selected">Очно</option>
        </select>
        </div>


        <div class="cont-input cont-btn">
            <input name="submit" id="submit" class="button_create" value="Зарегистрироваться" type="submit">
        </div>
        

    </form>


            </div>
                                  <div class="col">
                                      <aside role="complementary">



    


<style>
.smaller {
  font-size:80%;
}
.gray {
  color: #333;
}

.smaller-header {
  font-size: 20px;
}
.justify {
  text-align: justify;
  text-indent: 20px;
}
</style>


<div class="smaller">

<header>
  <h3 class="sr gray">Помощь в регистрации</h3>
</header>
  <div class="cta cta-welcome">
    <h3 class="gray smaller-header">Шаг первый</h3>
    <p class="justify">
      Заполните все поля формы для регистрации. После нажатия кнопки «Зарегистрироваться» вы перейдете на страницу формирования траектории посещения мероприятий конференции, а на вашу электронную почту будет отправлена персональная ссылка на вашу траекторию.
    </p>
  </div>


<div class="cta cta-nextsteps">
  <h3 class="gray smaller-header">Шаг второй</h3>
    <p class="justify">

      Перейдя по вашей персональной ссылке вы сможете изменить вашу траекторию посещения мероприятий конференции, а также прикрепить или удалить документы для публикации в электронном сборнике.
    </p>

</div>


  <div class="cta cta-help">
    <h3 class="gray smaller-header">Нужна помощь?</h3>
    <p class="justify">Нужна помощь в регистрации? Вы можете написать нам на <a href="mailto:notv@urfu.ru?subject=Нужна помощь в регистрации">электронную почту</a>.</p>
    <p>Tакже вы можете нам позвонить по  номеру телефона: 8 (343) 374-58-24</p>
  </div>

</div>

  </aside>
                                  
    </div>
  </div>
</div> <!-- /for-footer -->
</div>   

{% endblock %}

trajectory/templates/user/user_list.html
<h1>Users</h1>
        <ol>
            {% for user in object_list %}
            <li>{{ user.f }} {{ user.i }} {{ user.o }}</li>
            {% empty %}
            <li>No users</li>
            {% endfor %}
        </ol>